### ISSUE TITLE
cfg.yml for train diffusion prior

### ISSUE THREAD

**Issue by yjcaimeow** [nv-tlabs/LION#21]
Hi @ZENGXH ,

I successfully completed the first stage hvae training, but there is no cfg file when training the second diffusion prior.
1) Could you please provide the diffusion prior cfg file? 
2) Is it okay to use the first stage vae cfg.yml for the second diffusion prior training process? I have tried, but the beta shape maybe wrong. 
![image](https://user-images.githubusercontent.com/75470313/219910365-3acfc02a-388e-4b65-ba8d-351a16870495.png)

Best regards,
Yingjie

**Comment by ZENGXH** [comment]
Hi Yingjie, are you using [this ](https://github.com/nv-tlabs/LION/blob/061a2ca10f84def25eb99625d903ea03468fb426/script/train_prior.sh)file to launch prior training? 
The `cfg.yml` for prior is different from the first-stage, but we will load the first-stage `cfg.yml` through `--config` (as in the `train_prior.sh`)

Alternatively, I upload the prior config under the `config` folder now. Note that the `sde.vae_checkpoint` need to change to your stage-1 vae path.

**Comment by yjcaimeow** [comment]
Hi ZENGXH，

Thank you for your quick and patient reply.

Yes, I am training the second stage use "script/train_prior.sh". And I set the --config with the cfg.yml from first-stage vae folder. I understand you mean this experiment is okay, huh? If correct, I will keep training. By the way, is it convenient for you to share a loss curve of the second stage of training? The loss on my side is kept at around 1.9.

Thanks for the uploaded prior config and I will use it following experiments.

Best regards,
Yingjie

**Comment by ZENGXH** [comment]
Re 'experiment is okay': How do you fix the `beta` shape error? Is it caused by wrong config?  

Re loss curve: this is my curve for stage-2 training (on car): 
![image](https://user-images.githubusercontent.com/12856437/220015399-8572837f-4e8f-4678-b65a-f83ff2ad9268.png)
also the visualization of the reconstruction: 
![image](https://user-images.githubusercontent.com/12856437/220015476-f75bad18-87d7-49e2-90a6-499987b10371.png)
visualization of samples at different steps (top is output points, bottom is latent poitns):
![image](https://user-images.githubusercontent.com/12856437/220015737-75cc3456-46d3-49db-9911-6f3094a0ba32.png)
![image](https://user-images.githubusercontent.com/12856437/220015718-c099b059-64fb-48fc-865b-5d710053a965.png)

**Comment by yjcaimeow** [comment]
Hi ZENGXH，

Thank you for your quick and patient reply.
The beta from the first-stage cfg is wrong. And I retrain the second stage with the cfg you uploaded recently. The curve and final results are right.

Thanks again.

Best,
Yingjie
