### ISSUE TITLE
Testing on other categories

### ISSUE THREAD

**Issue by kakou34** [nv-tlabs/LION#26]
Hello, I am trying to reproduce the results obtained on the classes with small numbers of samples like mug  and bottle but the evaluation step is throwing this error 

`AssertionError: file not found: ./datasets/test_data/ref_val_mug.pt`

In the drive folder, you only provided the files for chair, car and airplane. Could you please assist me with how to generate these files for other categories? 
Thanks !

**Comment by ZENGXH** [comment]
I upload mug and bottle here: [bottle](https://drive.google.com/file/d/1MRl4EgW6-4hOrdRq_e2iGh348a0aCH5f/view?usp=share_link) [mug](https://drive.google.com/file/d/1lvJh2V94Nd7nZPcRqsCwW5oygsHOD3EE/view?usp=share_link) 

When you call the `compute_score` function, please also turn the `norm_box=True` since the reference data is normalized to [-1,1] already.
