### ISSUE TITLE
Why the reconstruction is so similar to the ground truth even in the early training stage in VAE?

### ISSUE THREAD

**Issue by OswaldoBornemann** [nv-tlabs/LION#52]
Why the reconstruction is so similar to the ground truth even in the early training stage in VAE?

**Comment by OswaldoBornemann** [comment]
I know that you referred something similar in issue [here](https://github.com/nv-tlabs/LION/issues/17). So I am very curious how you evaluate the reconstruction performance in your paper appendix, which is shown in table 24.

**Comment by OswaldoBornemann** [comment]
@ZENGXH I also would like to ask another question. It seems that the `input_pts` in `pointflow_datasets.py` is the same as the `tr_out`. So when you define `input_pts` as `noisy_input`, it just actually the same as the `val_x`? I am not sure if am I right. 
https://github.com/nv-tlabs/LION/blob/ca8129d8c00bb314e30e51992c3abfe002c625d9/trainers/base_trainer.py#L754

**Comment by OswaldoBornemann** [comment]
@ZENGXH What is the epoch of VAE that you used in the autoencoding experiment? Is that trained VAE be used for the diffusion training?

**Comment by ZENGXH** [comment]
> valuate the reconstruction performance in your paper appendix, which is shown in Table 23 and Table 24.

when we evaluate the reconstruction, we sample from the posterior, meaning that it's sampled from `N(network_output_mu, network_output_logsigma)` 

>  define input_pts as noisy_input, 

yes. the `noisy_input` in regular vae training is the same the input; I name it as `noisy` because we use different input points in exp `Encoder Fine-tuning for Voxel-Conditioned Synthesis and Denoising` under paper section 3.1

> epoch of vae

I use epoch 8000 for vae training, the last checkpoint is used for diffusion training

**Comment by OswaldoBornemann** [comment]
> 

Thank you very much.
